# Generated by Django 3.2.24 on 2024-02-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created',
            new_name='createdAt',
        ),
        migrations.AddField(
            model_name='item',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Finished', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(default='NULL', max_length=12),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
