# Generated by Django 3.2.24 on 2024-02-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_item_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock',
            new_name='in_stock',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='stock_status',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default='NONE', max_length=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(default='NONE', max_length=10),
        ),
    ]
