name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Python Dependency Installation
      # You may pin to the exact commit or the version.
      # uses: py-actions/py-dependency-install@30aa0023464ed4b5b116bd9fbdab87acf01a484e
      uses: py-actions/py-dependency-install@v4
    - name: Dockerhub login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASS: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - name: setup env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Docker image build
      run: docker build -t kaizntree_rest .
    - name: Dockerhub push
      run: docker push cgoyani/kaizntree_rest:latest
